interface/buckets/urls.py
from django.contrib import admin
from django.urls import path
from buckets import views

app_name = 'buckets'

urlpatterns = [
    # path('<uuid:id>/', views.show, name="show"),
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('', views.list, name="list"),
]

interface/datasets/urls.py
from django.contrib import admin
from django.urls import path
from datasets import views

app_name = 'datasets'

urlpatterns = [
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('<uuid:id>/', views.show, name="show"),
    path('', views.list, name="list"),
]

interface/function/urls.py
from django.contrib import admin
from django.urls import path
from function import views

app_name = 'function'

urlpatterns = [
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('<uuid:id>/submit', views.submit_code, name="submit"),
    path('<uuid:id>/', views.edit, name="edit"),
    path('', views.list, name="list"),
]

interface/interface/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('snapshots/', include("datasets.urls")),
    path('function/', include("function.urls")),
    path('devices/', include("workers.urls")),
    path('projects/', include("training.urls")),
    path('timeseries/', include("timeseries.urls")),
    path('buckets/', include("buckets.urls")),
    path('admin/', admin.site.urls),
]

interface/training/urls.py
from django.contrib import admin
from django.urls import path
from training import views

app_name = 'training'

urlpatterns = [
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('<uuid:id>/', views.edit, name="edit"),
    path('<uuid:id>/input', views.inputFeature, name="input"),
    path('<uuid:id>/output', views.outputFeature, name="output"),
    path('input/<uuid:id>', views.deleteInputFeature, name="inputFeature"),
    path('output/<uuid:id>', views.deleteOutputFeature, name="outputFeature"),
    path('<uuid:id>/models', views.deleteVersionFeature, name="deleteVersionFeature"),
    path('<uuid:id>/train', views.train, name="train"),
    path('model/<uuid:id>', views.view_model, name="model"),
    path('', views.list, name="list"),
]

interface/workers/urls.py
from django.contrib import admin
from django.urls import path
from workers import views

app_name = 'workers'

urlpatterns = [
    path('', views.list, name="list"),
    path('api', views.apilist, name="api-list"),
    path('deploy', views.deploy, name="deploy"),
]

interface/templates/base.html
{% load bootstrap5 %}

<head>
    <title>Edge Workers</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        body {
            height: 100%;
            width: 100%;
            position: absolute;
        }

        .container-fluid,
        .row-fluid {
            height: inherit;
        }
    </style>
</head>

<body>
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<header class="navbar navbar-dark sticky-top bg-primary flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">
        <i class="fa fa-cloud"></i>
        Edge Workers
    </a>
</header>

<div class="container-fluid">
    <div class="row row-fluid">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <div style=""><strong style="color:white">Inference</strong></div>
                        <a href="{% url "datasets:list" %}" class="nav-link {% if 'snapshot' in request.path %}active{% endif %} text-white" aria-current="page">
                            <i class="fa-solid fa-camera-retro"></i>
                            Data Snapshots
                        </a>
                        <a href="{% url "workers:list" %}" class="nav-link {% if 'devices' in request.path %}active{% endif %} text-white" aria-current="page">
                            <i class="fa-solid fa-microchip"></i>
                            Devices
                        </a>
                        <a href="{% url "function:list" %}" class="nav-link {% if 'function' in request.path %}active{% endif %} text-white" aria-current="page">
                            <i class="fa-solid fa-rocket"></i>
                            Functions
                        </a>
                        <a href="{% url "training:list" %}" class="nav-link {% if 'projects' in request.path %}active{% endif %} text-white" aria-current="page">
                            <i class="fa-solid fa-diagram-project"></i>
                            Projects
                        </a>
                        <div style="margin-top: 20px;"><strong style="color:white">Data Lake</strong></div>
                        <a href="{% url "timeseries:list" %}" class="nav-link {% if 'timeseries' in request.path %}active{% endif %} text-white" aria-current="page">
                            <i class="fa-solid fa-database"></i>
                            Time Series DB
                        </a>
                        <a href="{% url "buckets:list" %}" class="nav-link {% if 'buckets' in request.path %}active{% endif %} text-white" aria-current="page">
                            <i class="fa-solid fa-bucket"></i>
                            Buckets
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="chartjs-size-monitor">
                <div class="chartjs-size-monitor-expand">
                    <div class=""></div>
                </div>
                <div class="chartjs-size-monitor-shrink">
                    <div class=""></div>
                </div>
            </div>
            {% block content %}{% endblock content %}
        </main>
    </div>
</div>
</body>