interface/buckets/urls.py
from django.contrib import admin
from django.urls import path
from buckets import views

app_name = 'buckets'

urlpatterns = [
    # path('<uuid:id>/', views.show, name="show"),
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('', views.list, name="list"),
]

interface/datasets/urls.py
from django.contrib import admin
from django.urls import path
from datasets import views

app_name = 'datasets'

urlpatterns = [
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('<uuid:id>/', views.show, name="show"),
    path('', views.list, name="list"),
]

interface/interface/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('snapshots/', include("datasets.urls")),
    path('function/', include("function.urls")),
    path('devices/', include("workers.urls")),
    path('projects/', include("training.urls")),
    path('timeseries/', include("timeseries.urls")),
    path('buckets/', include("buckets.urls")),
    path('admin/', admin.site.urls),
]

interface/training/urls.py
from django.contrib import admin
from django.urls import path
from training import views

app_name = 'training'

urlpatterns = [
    path('<uuid:id>/delete', views.delete, name="delete"),
    path('<uuid:id>/', views.edit, name="edit"),
    path('<uuid:id>/input', views.inputFeature, name="input"),
    path('<uuid:id>/output', views.outputFeature, name="output"),
    path('input/<uuid:id>', views.deleteInputFeature, name="inputFeature"),
    path('output/<uuid:id>', views.deleteOutputFeature, name="outputFeature"),
    path('<uuid:id>/models', views.deleteVersionFeature, name="deleteVersionFeature"),
    path('<uuid:id>/train', views.train, name="train"),
    path('model/<uuid:id>', views.view_model, name="model"),
    path('', views.list, name="list"),
]

interface/training/models.py
import uuid

from django.db import models
from django.utils import timezone

from datasets.models import Dataset
from training.tasks import train

class MLModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(default=timezone.now, editable=False)
    name = models.CharField("Name", max_length=1024)
    bucket = models.CharField("Bucket", blank=True, default="", max_length=1024)

    def get_config(self):
        input_features = []
        for inputs in self.inputs.all():
            input_features.append(inputs.get_config())

        output_features = []
        for outputs in self.outputs.all():
            output_features.append(outputs.get_config())

        return {
            "input_features": input_features,
            "output_features": output_features,
        }

FEATURE_TYPE_CHOICES = (
    ("binary", "Binary"),
    ("numerical", "Numerical"),
    ("category", "Category"),
    ("bag", "Bag"),
    ("sequence", "Sequence"),
    ("vector", "Vector"),
    ("audio", "Audio"),
    ("date", "Date"),
    ("h3", "H3"),
    ("image", "Image"),
    ("timeseries", "Time Series"),
)


class InputFeatures(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(default=timezone.now, editable=False)
    name = models.CharField("Name", max_length=1024)
    type = models.CharField("Type", choices=FEATURE_TYPE_CHOICES, max_length=1024)
    model = models.ForeignKey(MLModel, on_delete=models.CASCADE, related_name="inputs")

    def get_config(self):
        return {
            "name": self.name,
            "type": self.type,
            'encoder': 'rnn',
            'embedding_size': 32,
            'state_size': 32
        }

class OutputFeatures(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(default=timezone.now, editable=False)
    name = models.CharField("Name", max_length=1024)
    type = models.CharField("Type", choices=FEATURE_TYPE_CHOICES, max_length=1024)
    model = models.ForeignKey(MLModel, on_delete=models.CASCADE, related_name="outputs")

    def get_config(self):
        return {
            "name": self.name,
            "type": self.type,
        }

class MLModelDataset(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(default=timezone.now, editable=False)
    dataset = models.ForeignKey(Dataset, null=True, on_delete=models.CASCADE)
    model = models.ForeignKey(MLModel, on_delete=models.CASCADE)


class MLModelVersion(models.Model):
    STATUS_CHOICES=(
        ("wait", "Wait to start"),
        ("training", "Training"),
        ("optimizing", "Optimizing"),
        ("error", "Error"),
        ("finished", "Finished"),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(default=timezone.now, editable=False)
    trained = models.DateTimeField(blank=True, null=True)
    status = models.CharField("Status", default="wait", choices=STATUS_CHOICES, max_length=50)
    dataset = models.ForeignKey(MLModelDataset, on_delete=models.CASCADE)
    model = models.ForeignKey(MLModel, on_delete=models.CASCADE, related_name="versions")
    evaluation_result = models.TextField("Evaluation Result")

    def train(self):
        train.delay(self.id)

interface/training/forms.py
from django import forms

from datasets.models import Dataset
from training.models import MLModel, MLModelDataset, InputFeatures, OutputFeatures, MLModelVersion


class MLModelForm(forms.ModelForm):
    class Meta:
        model = MLModel
        fields = ["name", "bucket"]
        help_texts = {
            'bucket': 'Where the model assets should be stored',
        }

class InputFeatureForm(forms.ModelForm):
    model = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=MLModel.objects.all())

    class Meta:
        model = InputFeatures
        fields = ["name", "type", "model"]


class OutputFeatureForm(forms.ModelForm):
    model = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=MLModel.objects.all())

    class Meta:
        model = OutputFeatures
        fields = ["name", "type", "model"]


class MLModelDatasetForm(forms.ModelForm):
    dataset = forms.ModelChoiceField(label="Snapshot", queryset=Dataset.objects.all())
    model = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=MLModel.objects.all())

    class Meta:
        model = MLModelDataset
        fields = ["dataset", "model"]


class MLModelVersionForm(forms.ModelForm):
    dataset = forms.ModelChoiceField(label="Data Snapshot", queryset=MLModelDataset.objects.all())
    model = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=MLModel.objects.all())

    class Meta:
        model = MLModelVersion
        fields = ["dataset", "model"]

interface/training/views.py
import base64
import json
import os

import humanize
from django.conf import settings
from django.contrib.sites import requests
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse

from buckets.models import Bucket
from training.forms import MLModelForm, MLModelDatasetForm, InputFeatureForm, OutputFeatureForm, MLModelVersionForm
from training.models import MLModel, MLModelDataset, InputFeatures, OutputFeatures, MLModelVersion


def list(req: HttpRequest):
    if req.method == "GET":
        return render(req, "list_training.html", {
            "objects": MLModel.objects.all(),
            "form": MLModelForm()
        })
    else:
        form = MLModelForm(req.POST)
        if form.is_valid():
            train = form.save()
            if not train.bucket:
                train.bucket = str(train.id)
                train.save()
            bucket = Bucket(name=train.bucket)
            bucket.save()
            return redirect(reverse("training:edit", args=[train.id]))
        else:
            return render(req, "list_training.html", {
                "form": MLModelForm()
            })


def edit(req: HttpRequest, id: str):
    if req.method == "GET":
        model = get_object_or_404(MLModel, id=id)
        form = MLModelDatasetForm(initial={'model': model.pk})
        form.fields['model'].queryset = MLModel.objects.filter(id=id)
        form.fields['dataset'].label_from_instance = lambda x: x.name
        trainform = MLModelVersionForm(initial={'model': model.pk})
        trainform.fields['dataset'].label_from_instance = lambda x: x.dataset.name
        return render(req, "edit_training.html", {
            "object": model,
            "objects": MLModelDataset.objects.filter(model=model),
            "datasetform": form,
            "inputform": InputFeatureForm(initial={'model': model.pk}),
            "outputform": OutputFeatureForm(initial={'model': model.pk}),
            "trainform": trainform
        })
    else:
        # TODO: theres a sec flaw here
        form = MLModelDatasetForm(req.POST)
        if form.is_valid():
            mldataset = form.save()
            return redirect(reverse("training:edit", args=[id]))


def inputFeature(req: HttpRequest, id: str):
    form = InputFeatureForm(req.POST)
    if form.is_valid():
        mldataset = form.save()
        return redirect(reverse("training:edit", args=[id]))


def deleteInputFeature(req: HttpRequest, id: str):
    if req.method == "POST":
        obj = get_object_or_404(InputFeatures, id=id)
        model_id = obj.model.id
        obj.delete()
        return redirect(reverse("training:edit", args=[model_id]))


def outputFeature(req: HttpRequest, id: str):
    form = OutputFeatureForm(req.POST)
    if form.is_valid():
        mldataset = form.save()
        return redirect(reverse("training:edit", args=[id]))

def deleteOutputFeature(req: HttpRequest, id: str):
    if req.method == "POST":
        obj = get_object_or_404(OutputFeatures, id=id)
        model_id = obj.model.id
        obj.delete()
        return redirect(reverse("training:edit", args=[model_id]))

def deleteVersionFeature(req: HttpRequest, id: str):
    if req.method == "POST":
        obj = get_object_or_404(MLModelVersion, id=id)
        model_id = obj.model.id
        obj.delete()
        return redirect(reverse("training:edit", args=[model_id]))

def train(req: HttpRequest, id: str):
    form = MLModelVersionForm(req.POST)
    if form.is_valid():
        mlversion = form.save()
        mlversion.train()
        return redirect(reverse("training:edit", args=[id]))


def delete(req: HttpRequest, id: str):
    if req.method == "POST":
        obj = get_object_or_404(MLModel, id=id)
        obj.delete()
        return redirect(reverse("training:list"))


def view_model(req: HttpRequest, id: str):
    obj = get_object_or_404(MLModelVersion, id=id)
    data = json.loads(obj.evaluation_result.replace("'", "\""));
    for key, _ in data.items():
        if key != "combined":
            model_bucket = os.path.join(settings.ROOT_BUCKET, obj.model.bucket or str(obj.model.id))
            model_version_path = os.path.join(model_bucket, str(obj.id))
            image_data = open(model_version_path + "/results/" + "learning_curves_" + key + "_loss.png", "rb").read()
            data[key]['loss_img'] = 'data:image/png;base64,{}'.format(base64.b64encode(image_data).decode('ascii'))
    return render(req, "view_model.html", {
        "object": obj,
        "evaluation_result": data,
        "duration": humanize.naturaldelta(obj.trained - obj.created)
    })

interface/training/templates/list_training.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Projects</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">
                <i class="fa fa-plus"></i>
                New
            </button>
        </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
        </tr>
      </thead>
      <tbody>
        {% for object in objects %}
            <tr>
                <td><a href="{% url "training:edit" object.pk %}">{{ object.name }}</a></td>
            </tr>
        {% endfor %}

      </tbody>
    </table>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form action="" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">New Model Training</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">New</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

interface/training/templates/view_model.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load fuzzy %}
{% load humanize %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ object.model.name }}
            <small class="text-muted"><code>{{ object.id }}</code></small>
        </h1>

        <div class="btn-toolbar mb-2 mb-md-0">
            <form style="margin-bottom: 0px;" action="{% url "training:deleteVersionFeature" object.pk %}"
                  method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-outline-danger">
                    <i class="fa fa-trash"></i>
                    Delete
                </button>
            </form>
        </div>
    </div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile"
                    type="button"
                    role="tab" aria-controls="profile" aria-selected="false">Model Details
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button"
                    role="tab" aria-controls="home" aria-selected="true">Evaluation
            </button>
        </li>
    </ul>
    <style>
        .card.col {
            margin-left: 5px;
            margin-right: 5px;
        }
    </style>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane active" id="profile" role="tabpanel" aria-labelledby="profile-tab"
             style="margin-top: 20px">
            <div class="row">
                <div class="card col">
                    <div class="card-body">
                        <h5 class="card-title">Details</h5>
                        <p class="card-text">
                        <dl>
                            <dt>ID</dt>
                            <dd><code>{{ object.id }}</code></dd>
                            <dt>Created at</dt>
                            <dd>{{ object.created|naturaltime }}</dd>
                            <dt>Training duration</dt>
                            <dd>{{ duration }}</dd>
                        </dl>
                        </p>
                    </div>
                </div>
                <div class="card col">
                    <div class="card-body">
                        <h5 class="card-title">Data Snapshot</h5>
                        <p class="card-text">
                        <dl>
                            <dt>Name</dt>
                            <dd>
                                <a href="{% url "datasets:show" object.dataset.dataset.id %}">{{ object.dataset.dataset.name }}</a>
                            </dd>
                            <dt>Mean</dt>
                            <dd>{{ object.dataset.dataset.mean }}</dd>
                            <dt>std</dt>
                            <dd>{{ object.dataset.dataset.std }}</dd>
                        </dl>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="home" role="tabpanel" aria-labelledby="home-tab"
             style="margin-top: 20px">
            {% for key, value in evaluation_result.items %}
                {% if key != "combined" %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><code>{{ key }}</code></h5>
                        <p class="card-text">
                        <dl>
                            {% for key, value in value.items %}
                                {% if key != "loss_img" %}
                                <dt>{{ key }}</dt>
                                <dd>{{ value }}</dd>
                                {% endif %}
                            {% endfor %}
                            <img src="{{ value.loss_img }}" alt="">
                        </dl>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

{% endblock %}